name: 12345678Reproduce hdiutil Resource Busy

on:
  workflow_dispatch:

jobs:
  build-dmg:
    runs-on: macos-13
    name: macOS Intel Repro Attempt

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install cmake

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build app
        run: cmake --build build --config Release

      - name: Interfere with CPack to simulate resource busy
        run: |
          echo "::group::Start CPack with interference"
          TEMP_DMG="build/_CPack_Packages/Darwin/DragNDrop/temp.dmg"
          
          # Run cpack in background to allow interference
          cpack --debug &

          CPACK_PID=$!

          # Give it time to generate the temp.dmg file
          sleep 2

          # Try to mount it while cpack is using it
          if [ -f "$TEMP_DMG" ]; then
            echo "Mounting temp.dmg to simulate conflict"
            hdiutil attach "$TEMP_DMG" || true
          else
            echo "No temp.dmg yet — skipping mount"
          fi

          # Wait for cpack to finish
          wait $CPACK_PID || true
          echo "::endgroup::"

      - name: Upload Artifacts (if any)
        uses: actions/upload-artifact@v4
        with:
          name: DMGArtifacts
          path: build/*.dmg
          if-no-files-found: warn
