name: Reproduce hdiutil Resource Busy

on:
  workflow_dispatch:

jobs:
  build-dmg:
    runs-on: macos-13
    name: macOS Intel Repro Attempt

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install cmake

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build App
        run: cmake --build build --config Release

      - name: Simulate interference during CPack
        run: |
          echo "::group::Start CPack with interference"
          TEMP_DMG="build/_CPack_Packages/Darwin/DragNDrop/temp.dmg"

          # Start CPack in background with verbose logs
          cpack --verbose --config build/CPackConfig.cmake &

          CPACK_PID=$!

          # Give CPack a moment to create temp.dmg
          sleep 2

          # Try to interfere with the disk image while CPack is using it
          if [ -f "$TEMP_DMG" ]; then
            echo "Attempting to mount temp.dmg to simulate hdiutil conflict..."
            hdiutil attach "$TEMP_DMG" || echo "Mount failed (expected if in use)"
          else
            echo "No temp.dmg yet — skipping interference"
          fi

          # Wait for CPack to finish
          wait $CPACK_PID || echo "CPack exited with error (may be expected)"
          echo "::endgroup::"

      - name: Upload DMG (if created)
        uses: actions/upload-artifact@v4
        with:
          name: DMGArtifacts
          path: build/*.dmg
          if-no-files-found: warn
