name: 9999Reproduce hdiutil Resource Busy

on:
  workflow_dispatch:

jobs:
  build-dmg:
    runs-on: macos-13
    name: macOS Intel Repro Attempt

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install cmake

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build app
        run: cmake --build build --config Release

      - name: Interfere with CPack to simulate resource busy
        run: |
          echo "::group::Start CPack with interference"
          TEMP_DMG="build/_CPack_Packages/Darwin/DragNDrop/temp.dmg"

          # Run CPack in the background with explicit config
          cpack --debug --config build/CPackConfig.cmake &
          CPACK_PID=$!

          # Wait for temp.dmg to appear (max 20s)
          for i in {1..20}; do
            if [ -f "$TEMP_DMG" ]; then
              echo "temp.dmg found at attempt $i"
              break
            fi
            sleep 1
          done

          if [ ! -f "$TEMP_DMG" ]; then
            echo "temp.dmg not found after waiting, skipping mount interference"
          else
            echo "Attempting to mount temp.dmg repeatedly to cause resource busy"
            for j in {1..5}; do
              hdiutil attach "$TEMP_DMG" -nobrowse -quiet || echo "Mount failed, maybe busy"
              sleep 1
              MOUNT_POINT=$(hdiutil info | grep "$TEMP_DMG" -B 5 | grep "/Volumes" | awk '{print $1}')
              if [ -n "$MOUNT_POINT" ]; then
                hdiutil detach "$MOUNT_POINT" -quiet || echo "Detach failed"
              fi
            done
          fi

          # Wait for CPack to finish
          wait $CPACK_PID || true
          echo "::endgroup::"

      - name: Upload Artifacts (if any)
        uses: actions/upload-artifact@v4
        with:
          name: DMGArtifacts
          path: |
            build/*.dmg
            *.dmg
            _CPack_Packages/**/*.dmg
          if-no-files-found: warn
