name: 12345678Reproduce hdiutil Resource Busy

on:
  workflow_dispatch:

jobs:
  build-dmg:
    runs-on: macos-13
    name: macOS Intel Repro Attempt

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install cmake

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build app
        run: cmake --build build --config Release

      - name: Simulate interference during CPack
        run: |
          echo "::group::Start CPack with interference"
          TEMP_DMG="build/_CPack_Packages/Darwin/DragNDrop/temp.dmg"

          # Run cpack in background with verbose output
          cpack --verbose --config build/CPackConfig.cmake &

          CPACK_PID=$!

          # Wait up to 10 seconds for temp.dmg to appear
          for i in {1..10}; do
            if [ -f "$TEMP_DMG" ]; then
              echo "Mounting temp.dmg to simulate conflict"
              hdiutil attach "$TEMP_DMG" || echo "Mount failed (this may be expected)"
              break
            fi
            sleep 1
          done

          # Wait for cpack to finish
          wait $CPACK_PID || echo "CPack exited with error (may be expected)"
          echo "::endgroup::"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: DMGArtifacts
          path: DMGRepro-*.dmg
          if-no-files-found: warn
