name: 9999Reproduce hdiutil Resource Busy

on:
  workflow_dispatch:

jobs:
  build-dmg:
    runs-on: macos-13
    name: macOS Intel Repro Attempt

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install cmake

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build app
        run: cmake --build build --config Release

      - name: Interfere with CPack to simulate resource busy
        run: |
          echo "::group::Start CPack with interference"
          TEMP_DMG="build/_CPack_Packages/Darwin/DragNDrop/temp.dmg"

          mkdir -p "$(dirname "$TEMP_DMG")"
          hdiutil create -size 10m -fs HFS+ -volname Dummy "$TEMP_DMG"
          hdiutil attach "$TEMP_DMG"

          # Run CPack which may fail due to temp.dmg being mounted
          cpack --debug --config build/CPackConfig.cmake || echo "CPack may have failed due to resource busy"

          # Detach simulated temp.dmg
          MOUNT_POINT=$(hdiutil info | grep "$TEMP_DMG" -B 5 | grep "/Volumes" | awk '{print $1}')
          if [ -n "$MOUNT_POINT" ]; then
            hdiutil detach "$MOUNT_POINT" || echo "Detach failed"
          fi

          echo "::endgroup::"

      - name: Upload Artifacts (if any)
        uses: actions/upload-artifact@v4
        with:
          name: DMGArtifacts
          path: |
            build/*.dmg
            *.dmg
            _CPack_Packages/**/*.dmg
          if-no-files-found: warn
