name: Reproduce Fastlane Simulator Bug

on:
  workflow_dispatch:

jobs:
  test-fastlane:
    runs-on: macos-14
    steps:
      - name: 🛠 Set up Xcode 16.2
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app
          xcodebuild -version

      - name: 📱 List Simulators
        run: xcrun simctl list devices

      - name: 🚀 Run Fastlane Scan on iPhone 16 Pro
        run: |
          which bundle || gem install bundler
          bundle install || gem install fastlane
          fastlane run scan device:"iPhone 16 Pro"
