name: Use Xcode 16.2 and Reproduce Simulator Issue

on:
  workflow_dispatch:

jobs:
  test-xcode-16_2:
    runs-on: macos-14

    steps:
      - name: Switch to Xcode 16.2
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app
          xcodebuild -version

      - name: List all available simulators
        run: |
          echo "Available simulators:"
          xcrun simctl list devices

      - name: Find and boot iPhone 16 Pro simulator
        run: |
          echo "Searching for iPhone 16 Pro simulator..."
          DEVICE_ID=$(xcrun simctl list devices | grep 'iPhone 16 Pro' | grep -v unavailable | awk -F '[()]' '{print $2}' | head -n 1)
          echo "Found device ID: $DEVICE_ID"

          if [ -z "$DEVICE_ID" ]; then
            echo "❌ ERROR: Could not find iPhone 16 Pro simulator"
            exit 1
          fi

          echo "✅ Booting simulator with ID $DEVICE_ID"
          xcrun simctl boot "$DEVICE_ID" || echo "⚠️ Failed to boot, might already be booted"
          xcrun simctl list | grep Booted
