name: Reproduce iPhone 16 Pro Emulator Issue

on: workflow_dispatch # Or any other trigger

jobs:
  test_simulator:
    runs-on: macos-14 # Specify the problematic image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Xcode 16.2
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app # Assuming Xcode 16.2 is pre-installed in the image
          xcodebuild -version

      - name: List Available Simulators (Confirm Presence)
        run: xcrun simctl list devices

      - name: Set up Ruby and Bundler
        run: |
          brew install ruby # Or your preferred Ruby installation method
          gem install bundler -NV

      - name: Create Gemfile and Install Fastlane
        run: |
          mkdir -p fastlane
          cd fastlane
          cat > Gemfile <<EOF
          source "https://rubygems.org"

          gem "fastlane"
          EOF
          bundle install

      - name: Create Minimal Fastfile
        run: |
          cd fastlane
          cat > Fastfile <<EOF
          default_platform(:ios)

          platform :ios do
            desc "Run tests"
            lane :scan_test do
              scan(device: "iPhone 16 Pro")
            end
          end
          EOF

      - name: Attempt to Run Fastlane Scan (Reproduce Error)
        run: cd fastlane && bundle exec fastlane scan_test || true # Allow the step to fail and show the error
