name: Validate Xcode 26.0 SDK by Building iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Select Xcode 26.0
      run: |
        echo "👉 Switching to Xcode 26.0..."
        sudo xcode-select -s /Applications/Xcode_26_beta.app/Contents/Developer
        xcodebuild -version

    - name: Show available SDKs
      run: xcodebuild -showsdks

    - name: Build iOS App using Xcode 26.0 SDK (no signing)
      run: |
        echo "📦 Building iOS app for device (iphoneos SDK)"
        xcodebuild \
          -project Fastlanedemoapp/Fastlanedemoapp.xcodeproj \
          -scheme Fastlanedemoapp \
          -sdk iphoneos \
          -configuration Debug \
          CODE_SIGNING_ALLOWED=NO \
          build

    - name: Show Build Settings (Verify SDK Used)
      run: |
        echo "🔍 Verifying SDKROOT used during build:"
        xcodebuild \
          -project Fastlanedemoapp/Fastlanedemoapp.xcodeproj \
          -scheme Fastlanedemoapp \
          -sdk iphoneos \
          -configuration Debug \
          -showBuildSettings | grep SDKROOT

    - name: Verify Build Output
      run: |
        echo "📂 Checking if app binary was built..."
        BUILD_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -name "*.app" | head -n 1)
        if [ -d "$BUILD_PATH" ]; then
          echo "✅ App was built at: $BUILD_PATH"
        else
          echo "❌ Build output not found!"
          exit 1
        fi
    
    - name: List Derived Data contents
      run: |
        echo "📁 Listing DerivedData for inspection..."
        ls -R ~/Library/Developer/Xcode/DerivedData


