name: Install PoCL 6.0.1

on:
  workflow_dispatch:

jobs:
  pocl:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-13]

    steps:
    - uses: actions/checkout@v4

    # Install PoCL if cache miss
    - name: Install PoCL 6.0.1 via Homebrew formula URL
      run: |
        # Download official PoCL 6.0.1 source tarball
          curl -L -o pocl-6.0.1.tar.gz https://github.com/pocl/pocl/releases/download/v6.0.1/pocl-6.0.1.tar.gz
      
          # Extract and build
          tar xf pocl-6.0.1.tar.gz
          cd pocl-6.0.1
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
          make -j$(sysctl -n hw.ncpu)
          sudo make install

    # Update PATH and PKG_CONFIG_PATH
    - name: Update PATH and PKG_CONFIG_PATH
      run: |
        echo "/usr/local/opt/pocl/bin" >> "$GITHUB_PATH"
        echo "/opt/homebrew/opt/pocl/bin" >> "$GITHUB_PATH"
        echo "PKG_CONFIG_PATH=/usr/local/opt/pocl/lib/pkgconfig:/opt/homebrew/opt/pocl/lib/pkgconfig:$PKG_CONFIG_PATH" >> "$GITHUB_ENV"

    # Verify PoCL installation
    - name: Verify PoCL installation
      run: |
        which poclcc || { echo "PoCL compiler not found"; exit 1; }
        pkg-config --modversion pocl || { echo "PoCL pkg-config failed"; exit 1; }
