name: Install and Find CMake Versions

on:
  workflow_dispatch:

jobs:
  install_and_find_cmake:
    runs-on: macos-15  # macOS 15 ARM (you can adjust to macOS version as needed)

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Homebrew (if not installed)
      - name: Install Homebrew
        run: |
          if ! which brew > /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi

      # Install CMake from Homebrew if available (use a specific available version)
      - name: Install CMake 3.31.5 from Homebrew
        run: |
          brew install cmake@3.31.5

      # Install CMake 3.31.0 from source (if Homebrew doesn't have it)
      - name: Install CMake 3.31.0 from source
        run: |
          CMAKE_VERSION=3.31.0
          curl -LO https://cmake.org/files/v3.31/cmake-${CMAKE_VERSION}.tar.gz
          tar -zxvf cmake-${CMAKE_VERSION}.tar.gz
          cd cmake-${CMAKE_VERSION}
          ./bootstrap
          make
          sudo make install
          cd ..
          rm -rf cmake-${CMAKE_VERSION}*

      # Find installation paths for CMake 3.31.0 and CMake 3.31.5
      - name: Find CMake installation paths
        run: |
          # Check where CMake 3.31.0 is installed
          cmake_3_31_0_path=$(find /opt/homebrew/Cellar/cmake/3.31.0/ -type f -name cmake || find /usr/local/Cellar/cmake/3.31.0/ -type f -name cmake)
          echo "CMake 3.31.0 installed at: $cmake_3_31_0_path"

          # Check where CMake 3.31.5 is installed
          cmake_3_31_5_path=$(find /opt/homebrew/Cellar/cmake/3.31.5/ -type f -name cmake || find /usr/local/Cellar/cmake/3.31.5/ -type f -name cmake)
          echo "CMake 3.31.5 installed at: $cmake_3_31_5_path"

      # Verify that CMake is installed successfully
      - name: Verify CMake versions
        run: |
          cmake --version
