# .github/workflows/ci.yml
name: CocoaPods CI Reproduction

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod repo update

      - name: Install Pods
        run: pod install --repo-update

      - name: Build with xcodebuild
        run: |
          xcodebuild -workspace TestApp.xcworkspace \
          -scheme TestApp \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          clean build

      - name: Run Fastlane Scan (optional)
        run: |
          gem install fastlane
          bundle exec fastlane scan
