name: Try to Reproduce hdiutil Resource Busy Bug

on: [workflow_dispatch]

jobs:
  repro-dmg-busy:
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        attempt: [1, 2, 3, 4, 5]  # Run multiple times to increase chance
    steps:
      - name: Create fake .app with payload
        run: |
          mkdir -p TestApp/Test.app/Contents/MacOS
          base64 /dev/urandom | head -c 10000000 > TestApp/Test.app/Contents/MacOS/FakeBinary
          chmod +x TestApp/Test.app/Contents/MacOS/FakeBinary

      - name: Add spotlight metadata
        run: |
          mdimport TestApp/Test.app || true

      - name: Background I/O stress during packaging
        run: |
          mkdir output
          (
            # Simulate I/O contention in background
            while true; do
              find TestApp/ > /dev/null 2>&1
              mdutil -E . > /dev/null 2>&1
              sleep 0.1
            done
          ) &
          PID=$!

          # Try to create the DMG
          set +e
          hdiutil create -volname "TestApp" \
                         -srcfolder TestApp/Test.app \
                         -ov \
                         -format UDZO \
                         output/TestApp_${{ matrix.attempt }}.dmg -verbose
          STATUS=$?
          kill $PID
          wait $PID 2>/dev/null || true
          exit $STATUS

      - name: Show open dmg handles (if failed)
        if: failure()
        run: |
          echo "🔍 Listing open file handles:"
          lsof | grep .dmg || true

      - name: Upload DMG
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: DMG-Attempt-${{ matrix.attempt }}
          path: output/*.dmg
