name: Reproduce iOS Simulator Issue

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show available simulators
        run: xcrun simctl list devices

      - name: Build for testing with test plan
        run: |
          xcodebuild -project Test.xcodeproj \
            -scheme DEV \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest' \
            -testPlan UnitTests \
            build-for-testing \
            -derivedDataPath build
