name: Reproduce Simulator Destination Error

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-14

    steps:
      - name: Set up dummy Xcode project
        run: |
          mkdir DummyApp
          cd DummyApp
          echo '' > main.swift
          swift package init --type executable
          swift package generate-xcodeproj
          mv DummyApp.xcodeproj Test.xcodeproj

      - name: Try running tests on unavailable simulator
        run: |
          xcodebuild -project Test.xcodeproj \
            -scheme DummyApp \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest' \
            build-for-testing
