name: Reproduce create-dmg Finder Timeout

on:
  workflow_dispatch:

jobs:
  create-dmg-fail:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create dummy .app bundle with bloat
        run: |
          mkdir -p TestApp.app/Contents/MacOS
          echo -e '#!/bin/bash\necho "Test App Running!"' > TestApp.app/Contents/MacOS/TestApp
          chmod +x TestApp.app/Contents/MacOS/TestApp
          # Add dummy bloat to increase DMG size
          dd if=/dev/zero of=TestApp.app/Contents/MacOS/bloatfile bs=1m count=100
          # Add dummy Info.plist
          mkdir -p TestApp.app/Contents
          echo '<?xml version="1.0"?><plist version="1.0"><dict><key>CFBundleExecutable</key><string>TestApp</string></dict></plist>' > TestApp.app/Contents/Info.plist

      - name: Download dummy background image
        run: |
          mkdir -p tmp
          curl -L -o tmp/dmg-background.png https://raw.githubusercontent.com/github/explore/main/topics/mac/mac.png

      - name: Run create-dmg (expect AppleScript error)
        run: |
          create-dmg \
            --background "tmp/dmg-background.png" \
            --hide-extension "TestApp.app" \
            --volname "TestProject" \
            --window-pos 400 240 \
            --window-size 356 552 \
            --icon-size 124 \
            --icon "TestApp.app" 178 183 \
            --app-drop-link 178 371 \
            TestApp.dmg \
            TestApp.app
