name: Reproduce create-dmg AppleScript Timeout

on:
  workflow_dispatch:

jobs:
  create-dmg-timeout:
    runs-on: macos-15
    timeout-minutes: 5

    steps:
      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create dummy .app with “xcarchive-like” naming and bloat
        run: |
          mkdir -p "Archive/MyApp CI Internal.app/Contents/MacOS"
          echo -e '#!/bin/bash\necho "Hello from MyApp!"' > "Archive/MyApp CI Internal.app/Contents/MacOS/MyApp"
          chmod +x "Archive/MyApp CI Internal.app/Contents/MacOS/MyApp"
          dd if=/dev/zero of="Archive/MyApp CI Internal.app/Contents/MacOS/bloatfile" bs=1m count=200

      - name: Download background image
        run: |
          mkdir -p resources/release
          curl -L -s -o resources/release/dmg-background@2x.png \
            https://raw.githubusercontent.com/github/explore/main/topics/mac/mac.png

      - name: Run create-dmg with full customization
        run: |
          create-dmg \
            --background "resources/release/dmg-background@2x.png" \
            --hide-extension "MyApp CI Internal.app" \
            --volname "MyApp CI Internal" \
            --window-pos 400 240 \
            --window-size 356 552 \
            --icon-size 124 \
            --icon "MyApp CI Internal.app" 178 183 \
            --app-drop-link 178 371 \
            MyAppCI.dmg \
            "Archive/MyApp CI Internal.app"

      - name: Show result or error
        run: |
          echo "DMG creation completed (check logs for AppleScript errors)."
