name: Test create-dmg on macOS 15 ARM

on:
  workflow_dispatch:

jobs:
  test-create-dmg:
    runs-on: macos-15
    name: Reproduce AppleScript Timeout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up test app structure
        run: |
          mkdir -p TestApp.app/Contents/MacOS
          echo -e '#!/bin/bash\necho "Hello from TestApp!"' > TestApp.app/Contents/MacOS/TestApp
          chmod +x TestApp.app/Contents/MacOS/TestApp

          mkdir -p resources/release
          curl -o resources/release/dmg-background@2x.png https://via.placeholder.com/600x400.png?text=Background
          
          cp resources/release/dmg-background@2x.png TestApp.app/icon.icns

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Run create-dmg with Finder customization
        run: |
          create-dmg \
            --background "./resources/release/dmg-background@2x.png" \
            --hide-extension "TestApp.app" \
            --volname "TestProject" \
            --window-pos 400 240 \
            --window-size 356 552 \
            --icon-size 124 \
            --icon "TestApp.app" 178 183 \
            --app-drop-link 178 371 \
            ./TestApp.app \
            TestApp.dmg

      - name: List DMG
        run: ls -lh *.dmg || echo "DMG not created"
