name: Test create-dmg on macOS 15 ARM

on:
  workflow_dispatch:

jobs:
  test-create-dmg:
    name: Reproduce create-dmg Issue
    runs-on: macos-15-arm64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up TestApp.app
        run: |
          mkdir -p TestApp.app/Contents/MacOS
          echo -e '#!/bin/bash\necho "Hello from TestApp!"' > TestApp.app/Contents/MacOS/TestApp
          chmod +x TestApp.app/Contents/MacOS/TestApp

          mkdir -p resources/release
          curl -L -o resources/release/dmg-background@2x.png https://raw.githubusercontent.com/github/explore/main/topics/macos/macos.png

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create DMG using create-dmg
        run: |
          mkdir -p out
          create-dmg \
            --background "$PWD/resources/release/dmg-background@2x.png" \
            --hide-extension "TestApp.app" \
            --volname "TestProject" \
            --window-pos 400 240 \
            --window-size 356 552 \
            --icon-size 124 \
            --icon "TestApp.app" 178 183 \
            --app-drop-link 178 371 \
            "$PWD/TestApp.app" \
            "$PWD/out/TestApp.dmg"

      - name: Show DMG output
        run: ls -lh out || echo "DMG not created"
