name: Reproduce create-dmg AppleScript timeout

on:
  workflow_dispatch:

jobs:
  create-dmg-test:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Prepare dummy app bundle
        run: |
          mkdir -p TestApp.app/Contents/MacOS
          echo -e '#!/bin/bash\necho "Hello from TestApp!"' > TestApp.app/Contents/MacOS/TestApp
          chmod +x TestApp.app/Contents/MacOS/TestApp

      - name: Ensure background image exists
        run: |
          mkdir -p resources/release
          curl -L -o resources/release/dmg-background@2x.png \
            https://raw.githubusercontent.com/github/explore/main/topics/macos/macos.png

      - name: Create DMG with Finder customization (should fail)
        run: |
          create-dmg \
            --background "resources/release/dmg-background@2x.png" \
            --hide-extension "TestApp.app" \
            --volname "TestProject" \
            --window-pos 400 240 \
            --window-size 356 552 \
            --icon-size 124 \
            --icon "TestApp.app" 178 183 \
            --app-drop-link 178 371 \
            "TestApp.app" \
            "TestApp.dmg"
