name: sangeeeth Reproduce hdiutil "Resource busy" Error

on:
  workflow_dispatch:
    inputs:
      repeat:
        description: "Number of times to repeat DMG creation"
        default: "10"
        required: false

jobs:
  repro-dmg:
    runs-on: macos-13
    name: Repro – hdiutil Test

    steps:
      - name: Create dummy .app bundle with large binary
        run: |
          mkdir -p MyApp.app/Contents/MacOS
          base64 /dev/urandom | head -c 10000000 > MyApp.app/Contents/MacOS/Payload
          chmod +x MyApp.app/Contents/MacOS/Payload
          echo "Created dummy .app bundle"

      - name: Make output dir
        run: mkdir output

      - name: Attempt hdiutil DMG creation multiple times
        run: |
          for i in $(seq 1 ${{ github.event.inputs.repeat }}); do
            echo "======== Attempt $i ========"
            hdiutil create -volname "TestApp" \
                           -srcfolder MyApp.app \
                           -ov -format UDZO \
                           output/TestApp_$i.dmg && echo "✅ Success on attempt $i" && continue

            echo "❌ Failed on attempt $i"
            echo "::warning::Trying to collect diagnostics for hdiutil failure"
            lsof | grep .dmg || true
            ps aux | grep hdiutil || true
            exit 1
          done

      - name: Upload last DMG (if any)
        uses: actions/upload-artifact@v4
        with:
          name: Last-DMG
          path: output/*.dmg
