# .github/workflows/repro-create-dmg.yml
name: sangeeth htutil

on:
  workflow_dispatch:

jobs:
  create-dmg:
    runs-on: macos-13
    steps:
      - name: Clone create-dmg
        run: |
          git clone https://github.com/create-dmg/create-dmg.git
          chmod +x create-dmg/create-dmg

      - name: Create dummy .app bundle
        run: |
          mkdir -p app/Sample.app/Contents/MacOS
          touch app/Sample.app/Contents/MacOS/Sample

      - name: Create DMG
        run: |
          ./create-dmg/create-dmg \
            --volname "Sample" \
            --window-size 500 300 \
            --icon-size 100 \
            --icon "Sample.app" 125 150 \
            --app-drop-link 375 150 \
            Sample.dmg \
            app/
