name: sangeeth Reproduce hdiutil Resource Busy Error (Heavy Stress Test)

on:
  workflow_dispatch:
    inputs:
      loops:
        description: "Number of DMG creation loops"
        required: false
        default: "20"
      payload_size_mb:
        description: "Payload size in MB"
        required: false
        default: "10"

jobs:
  reproduce-error:
    runs-on: macos-13
    name: hdiutil Stress Test

    steps:
      - name: Setup environment info
        run: |
          echo "macOS version:"
          sw_vers
          echo "Runner image info:"
          system_profiler SPSoftwareDataType

      - name: Disable Spotlight indexing
        run: |
          echo "Disabling Spotlight to reduce interference"
          sudo mdutil -i off /

      - name: Create realistic .app bundle (~${{ github.event.inputs.payload_size_mb }}MB)
        run: |
          echo "Creating Sample.app with random payload..."
          mkdir -p TestApp/Sample.app/Contents/MacOS
          base64 /dev/urandom | head -c $((${{ github.event.inputs.payload_size_mb }} * 1000000)) > TestApp/Sample.app/Contents/MacOS/Payload
          chmod +x TestApp/Sample.app/Contents/MacOS/Payload

      - name: Create output directory
        run: mkdir output

      - name: Loop to create multiple DMGs (stress test)
        run: |
          loops=${{ github.event.inputs.loops }}
          echo "Creating $loops DMGs..."
          for i in $(seq 1 $loops); do
            echo "===================="
            echo "DMG attempt #$i"
            echo "===================="
            hdiutil create -volname "TestApp$i" \
                           -srcfolder TestApp/Sample.app \
                           -ov -format UDZO \
                           output/TestApp_$i.dmg || {
              echo "::error::DMG creation failed at attempt $i"
              echo "Running lsof and ps diagnostics..."
              lsof | grep .dmg || true
              ps aux | grep hdiutil || true
              exit 1
            }
          done

      - name: Upload last 5 DMGs if successful
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Final-DMGs
          path: output/TestApp_*.dmg
