# .github/workflows/repro-hdiutil-error.yml
name: sangeeth - Reproduce hdiutil Issue

on:
  workflow_dispatch:

jobs:
  create-dmg:
    runs-on: macos-13
    steps:
      - name: Create folder and dummy file
        run: |
          mkdir myapp
          touch myapp/dummy.txt

      - name: Create DMG using hdiutil
        run: |
          hdiutil create -volname "TestDMG" -srcfolder myapp -ov -format UDZO "test.dmg"
