name: iOS Fastlane Tests

on:
  workflow_dispatch:

jobs:
  ios-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15]
        include:
          - os: macos-14
            xcode: Xcode_15.2.app
          - os: macos-15
            xcode: Xcode_16.2.app

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Fastlane
        run: gem install fastlane

      - name: Set Xcode version via Fastlane
        working-directory: Fastlanedemoapp
        run: fastlane setup_xcode_version xcodeVersionGit:"${{ matrix.xcode }}"

      - name: Run Fastlane tests
        working-directory: Fastlanedemoapp
        run: fastlane test
