name: sdk-xcode macos-15 problem

on:
  workflow_dispatch:
  push:
    branches: '*'

jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        platform: 
          - macos-13
          - macos-14
          - macos-15

    runs-on: ${{ matrix.platform }}

    steps:
      - run: xcrun -f cc
      - run: xcrun -f c++
      - run: xcrun -f ld
      - run: xcrun --show-sdk-path 
      - run: xcode-select -p
  
      - run: |
          echo "👉 xcode-select path:"
          xcode-select -p
          echo "👉 xcrun cc:"
          xcrun -f cc
          echo "👉 SDK path:"
          xcrun --show-sdk-path
          echo "👉 Verifying compiler version..."
          xcrun cc --version
          echo "👉 Compiling a simple C program using selected SDK..."
          echo '#include <stdio.h>' > test.c
          echo 'int main() { printf("Xcode SDK Test\\n"); return 0; }' >> test.c
          xcrun cc test.c -o test.out
          ./test.out
          echo "✅ C compilation succeeded with selected SDK!"
          echo "👉 Checking SDK headers (e.g., stdio.h)..."
          find "$(xcrun --show-sdk-path)" -name stdio.h | head -n 5
