name: susmitha issue

on:
  workflow_dispatch:

env:
  XCODE_VERSION: Xcode_16.3.app

jobs:
  test:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Fastlane
        run: brew install fastlane

      - name: Pre-Fastlane Debug Info
        run: |
          echo "===== BEFORE FASTLANE ====="
          echo "DEVELOPER_DIR=$DEVELOPER_DIR"
          xcode-select -p
          xcrun --find xcodebuild
          xcodebuild -version

      - name: Run Fastlane Setup
        run: fastlane setup_xcode_version xcodeVersionGit:"$XCODE_VERSION"

      - name: Post-Fastlane Debug Info
        run: |
          echo "===== AFTER FASTLANE ====="
          echo "DEVELOPER_DIR=$DEVELOPER_DIR"
          xcode-select -p
          xcrun --find xcodebuild
          xcodebuild -version
