name: Repro Xcode Version Selection

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-14-arm

    env:
      XCODE_VERSION: "Xcode_16.3.app"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Default Xcode Info
        run: |
          echo "🧾 Default Xcode Info BEFORE anything:"
          echo "DEVELOPER_DIR=$DEVELOPER_DIR"
          xcode-select -p
          xcrun --find xcodebuild
          xcodebuild -version

      - name: Setup Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'

      - name: Install Gems
        run: bundle install
        working-directory: Fastlanedemoapp/

      - name: Run Fastlane Lane to Set Xcode Version
        run: bundle exec fastlane setup_xcode_version xcodeVersionGit:"$XCODE_VERSION"
        working-directory: Fastlanedemoapp/

      - name: Print Xcode Info AFTER Fastlane xcode_select
        run: |
          echo "🧾 Xcode Info AFTER fastlane xcode_select:"
          echo "DEVELOPER_DIR=$DEVELOPER_DIR"
          xcode-select -p
          xcrun --find xcodebuild
          xcodebuild -version

      - name: Run Fastlane Tests
        run: bundle exec fastlane test
        working-directory: Fastlanedemoapp/
