name: Reproduce Xcode Selection Issue

on:
  workflow_dispatch:
    inputs:
      xcode_app_name:
        description: 'Xcode app name to select (e.g., Xcode_16.3.app)'
        required: true
        default: 'Xcode_16.3.app'
      xcode_developer_dir:
        description: 'Full path to Xcode.app/Contents/Developer (optional, overrides app_app_name)'
        required: false
        default: ''

jobs:
  check_xcode_selection:
    runs-on: macos-15-arm # CRITICAL: Specifying the runner from the issue

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Installed Xcode Versions on Runner
        run: |
          echo "=========================================="
          echo "DEBUG: LISTING ALL XCODE APPS IN /Applications"
          echo "=========================================="
          ls -la /Applications | grep "Xcode" || echo "No Xcode apps found or permission issue"
          echo "=========================================="

      - name: Set Target Xcode Path Variable
        id: set_xcode_path
        run: |
          if [ -n "${{ github.event.inputs.xcode_developer_dir }}" ]; then
            echo "XCODE_DEV_PATH=${{ github.event.inputs.xcode_developer_dir }}" >> $GITHUB_ENV
          else
            echo "XCODE_DEV_PATH=/Applications/${{ github.event.inputs.xcode_app_name }}/Contents/Developer" >> $GITHUB_ENV
          fi
          echo "Target Xcode Developer Path set to: $XCODE_DEV_PATH"

      - name: Debug Xcode BEFORE selection attempt (Initial State)
        run: |
          echo "=========================================="
          echo "DEBUG: XCODE STATE BEFORE ANY SELECTION ATTEMPTS"
          echo "=========================================="
          echo "DEVELOPER_DIR (Environment Variable): '$DEVELOPER_DIR'"
          xcode-select -p || echo "xcode-select path not set or command failed"
          xcrun --find xcodebuild || echo "xcodebuild not found by xcrun or command failed"
          xcodebuild -version || echo "xcodebuild -version command failed"
          echo "=========================================="

      - name: Attempt to select Xcode (Direct 'sudo xcode-select -s')
        run: |
          echo "Attempting direct 'sudo xcode-select -s $XCODE_DEV_PATH'"
          sudo xcode-select -s "$XCODE_DEV_PATH" || true
          echo "Direct 'xcode-select -s' command executed. Check subsequent debug for effect."

      - name: Debug Xcode AFTER Direct Selection
        run: |
          echo "=========================================="
          echo "DEBUG: XCODE STATE AFTER DIRECT 'xcode-select -s'"
          echo "=========================================="
          echo "DEVELOPER_DIR (Environment Variable): '$DEVELOPER_DIR'"
          xcode-select -p || echo "xcode-select path not set or command failed"
          xcrun --find xcodebuild || echo "xcodebuild not found by xcrun or command failed"
          xcodebuild -version || echo "xcodebuild -version command failed"
          echo "=========================================="

      # --- Fastlane related steps (to mimic original report) ---
      - name: Setup Ruby and Bundler for Fastlane
        uses: ruby/setup-ruby@v1
        # CORRECTED INDENTATION FOR 'working-directory'
        working-directory: ${{ github.workspace }}/fastlane_xcode_test 
        with:
          ruby-version: '3.3.0' 
          bundler-cache: true 

      - name: Create Temporary Fastlane Setup (Gemfile & Fastfile)
        run: |
          # Create a temporary fastlane directory and Fastfile at the repo root
          mkdir -p ${{ github.workspace }}/fastlane_xcode_test
          cd ${{ github.workspace }}/fastlane_xcode_test

          # Create a minimal Gemfile for Fastlane
          cat > Gemfile <<EOF
          source "https://rubygems.org"
          gem "fastlane"
          EOF

          # Create a minimal Fastfile for the xcode_select lane
          mkdir -p fastlane # Fastlane expects its Fastfile in a 'fastlane' sub-directory
          cat > fastlane/Fastfile <<EOF
          default_platform(:ios)

          lane :setup_xcode_version do |options|
            xcode_select(options[:xcodeDeveloperDir])
          end
          EOF
          echo "Temporary Fastlane setup created in ${{ github.workspace }}/fastlane_xcode_test"
        working-directory: ${{ github.workspace }} # This step runs from repo root to create the folder

      - name: Install Fastlane Gems for Temporary Setup
        run: bundle install # This will use the Gemfile just created
        working-directory: ${{ github.workspace }}/fastlane_xcode_test # Run bundle install from here

      - name: Run Fastlane Xcode Selection Lane
        run: |
          echo "Attempting selection via Fastlane lane: setup_xcode_version"
          bundle exec fastlane setup_xcode_version xcodeDeveloperDir:"$XCODE_DEV_PATH" || true
        working-directory: ${{ github.workspace }}/fastlane_xcode_test # Run from temporary fastlane dir

      - name: Debug Xcode AFTER Fastlane Selection
        run: |
          echo "=========================================="
          echo "DEBUG: XCODE STATE AFTER FASTLANE SELECTION"
          echo "=========================================="
          echo "DEVELOPER_DIR (Environment Variable): '$DEVELOPER_DIR'"
          xcode-select -p || echo "xcode-select path not set or command failed"
          xcrun --find xcodebuild || echo "xcodebuild not found by xcrun or command failed"
          xcodebuild -version || echo "xcodebuild -version command failed"
          echo "=========================================="
