name: Reproduce Xcode Selection Issue

on:
  workflow_dispatch:
    inputs:
      # Input for the Xcode app name, default to 16.3 as in the original issue
      xcode_app_name:
        description: 'Xcode app name to select (e.g., Xcode_16.3.app)'
        required: true
        default: 'Xcode_16.3.app'
      # Optional: Input for the full developer directory path if needed, overrides app_name
      xcode_developer_dir:
        description: 'Full path to Xcode.app/Contents/Developer (optional, overrides app_app_name)'
        required: false
        default: ''

jobs:
  check_xcode_selection:
    runs-on: macos-15-arm # CRITICAL: Specifying the runner from the issue

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Installed Xcode Versions on Runner
        run: |
          echo "=========================================="
          echo "DEBUG: LISTING ALL XCODE APPS IN /Applications"
          echo "=========================================="
          ls -la /Applications | grep "Xcode" || echo "No Xcode apps found or permission issue"
          echo "=========================================="

      - name: Set Target Xcode Path Variable
        id: set_xcode_path
        run: |
          # Determine the full developer path based on input
          if [ -n "${{ github.event.inputs.xcode_developer_dir }}" ]; then
            echo "XCODE_DEV_PATH=${{ github.event.inputs.xcode_developer_dir }}" >> $GITHUB_ENV
          else
            # Construct path based on app name input
            echo "XCODE_DEV_PATH=/Applications/${{ github.event.inputs.xcode_app_name }}/Contents/Developer" >> $GITHUB_ENV
          fi
          echo "Target Xcode Developer Path set to: $XCODE_DEV_PATH"

      - name: Debug Xcode BEFORE selection attempt (Initial State)
        run: |
          echo "=========================================="
          echo "DEBUG: XCODE STATE BEFORE ANY SELECTION ATTEMPTS"
          echo "=========================================="
          echo "DEVELOPER_DIR (Environment Variable): '$DEVELOPER_DIR'" # Use single quotes to see if it's empty
          echo "xcode-select -p Output:"
          xcode-select -p || echo "xcode-select path not set or command failed"
          echo "xcrun --find xcodebuild Output:"
          xcrun --find xcodebuild || echo "xcodebuild not found by xcrun or command failed"
          echo "xcodebuild -version Output:"
          xcodebuild -version || echo "xcodebuild -version command failed"
          echo "=========================================="

      - name: Attempt to select Xcode (Direct 'sudo xcode-select -s')
        run: |
          echo "Attempting direct 'sudo xcode-select -s $XCODE_DEV_PATH'"
          # Use '|| true' to allow workflow to continue and print debug info even if this fails
          sudo xcode-select -s "$XCODE_DEV_PATH" || true
          echo "Direct 'xcode-select -s' command executed. Check subsequent debug for effect."

      - name: Debug Xcode AFTER Direct Selection
        run: |
          echo "=========================================="
          echo "DEBUG: XCODE STATE AFTER DIRECT 'xcode-select -s'"
          echo "=========================================="
          echo "DEVELOPER_DIR (Environment Variable): '$DEVELOPER_DIR'"
          echo "xcode-select -p Output:"
          xcode-select -p || echo "xcode-select path not set or command failed"
          echo "xcrun --find xcodebuild Output:"
          xcrun --find xcodebuild || echo "xcodebuild not found by xcrun or command failed"
          echo "xcodebuild -version Output:"
          xcodebuild -version || echo "xcodebuild -version command failed"
          echo "=========================================="

      # --- Fastlane related steps (to mimic original report) ---
      # These steps set up Fastlane in an isolated, temporary directory for this test
      - name: Setup Ruby and Bundler for Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0' # Use a specific version known to be on macos-15-arm runners
          bundler-cache: true # Caches gems via Gemfile.lock (looks in working-directory)
        working-directory: ${{ github.workspace }}/fastlane_xcode_test # This will be the context for bundle install

      - name: Create Temporary Fastlane Setup (Gemfile & Fastfile)
        run: |
          # Create a temporary fastlane directory and Fastfile at the repo root
          mkdir -p ${{ github.workspace }}/fastlane_xcode_test
          cd ${{ github.workspace }}/fastlane_xcode_test

          # Create a minimal Gemfile for Fastlane
          cat > Gemfile <<EOF
          source "https://rubygems.org"
          gem "fastlane"
          EOF

          # Create a minimal Fastfile for the xcode_select lane
          mkdir -p fastlane # Fastlane expects its Fastfile in a 'fastlane' sub-directory
          cat > fastlane/Fastfile <<EOF
          default_platform(:ios)

          lane :setup_xcode_version do |options|
            xcode_select(options[:xcodeDeveloperDir])
          end
          EOF
          echo "Temporary Fastlane setup created in ${{ github.workspace }}/fastlane_xcode_test"
        # This step runs from the repo root to create the 'fastlane_xcode_test' folder
        working-directory: ${{ github.workspace }} 

      - name: Install Fastlane Gems for Temporary Setup
        run: bundle install # This will use the Gemfile just created
        working-directory: ${{ github.workspace }}/fastlane_xcode_test # Run bundle install from here

      - name: Run Fastlane Xcode Selection Lane
        run: |
          echo "Attempting selection via Fastlane lane: setup_xcode_version"
          # Execute Fastlane from the temporary directory containing its Gemfile and fastlane/ directory
          bundle exec fastlane setup_xcode_version xcodeDeveloperDir:"$XCODE_DEV_PATH" || true
        working-directory: ${{ github.workspace }}/fastlane_xcode_test # Run from temporary fastlane dir

      - name: Debug Xcode AFTER Fastlane Selection
        run: |
          echo "=========================================="
          echo "DEBUG: XCODE STATE AFTER FASTLANE SELECTION"
          echo "=========================================="
          echo "DEVELOPER_DIR (Environment Variable): '$DEVELOPER_DIR'"
          echo "xcode-select -p Output:"
          xcode-select -p || echo "xcode-select path not set or command failed"
          echo "xcrun --find xcodebuild Output:"
          xcrun --find xcodebuild || echo "xcodebuild not found by xcrun or command failed"
          echo "xcodebuild -version Output:"
          xcodebuild -version || echo "xcodebuild -version command failed"
          echo "=========================================="
