name: Check Preinstalled Node, Yarn, and pnpm Versions

on:
  workflow_dispatch:

jobs:
  check-versions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14-arm64, macos-15-arm64]

    steps:
      - name: Print Node.js version
        run: node --version

      - name: Print npm version
        run: npm --version

      - name: Print Yarn version
        run: yarn --version

      - name: Print pnpm version (may fail if not preinstalled)
        continue-on-error: true
        run: pnpm --version
